### ISSUE TITLE
Make the App Responsive

### ISSUE THREAD

**Issue by MarcoMorawec** [tpetrini/nomster#1]
I suggest you include the mobile meta tag ;)

**Comment by atxnow** [comment]
Good call!  

I found and followed the instructions on: https://css-tricks.com/snippets/html/responsive-meta-tag/

Here is my updated prod env: https://nomster-tom-petrini.herokuapp.com/

Am I correct?

Now to fix the pagination feature.

**Comment by MarcoMorawec** [comment]
@tpetrini :+1: 

Looks like [this commit](https://github.com/tpetrini/nomster/commit/2658e47c840c18fee61cd7724e4fcd6b854a6eef) did the trick :)
