### ISSUE TITLE
Cleaning up the root page

### ISSUE THREAD

**Issue by MarcoMorawec** [tpetrini/nomster#2]
You have the pagination feature showing above the image slider on your home page.

I suggest you only show it at the very bottom of the page. Here's what I'm seeing:

![screen shot 2015-06-07 at 1 05 09 pm](https://cloud.githubusercontent.com/assets/1474717/8025017/02904906-0d16-11e5-8b01-a97d4dee6e9b.png)

**Comment by atxnow** [comment]
Right on!  Just fixed it. 

https://nomster-tom-petrini.herokuapp.com/
